export const EMPTY_QUOTES = [
  { text: "行到水穷处，坐看云起时。", source: "王维《终南别业》" },
  { text: "山重水复疑无路，柳暗花明又一村。", source: "陆游《游山西村》" },
  { text: "长风破浪会有时，直挂云帆济沧海。", source: "李白《行路难》" },
  { text: "欲穷千里目，更上一层楼。", source: "王之涣《登鹳雀楼》" },
  { text: "海内存知己，天涯若比邻。", source: "王勃《送杜少府之任蜀州》" },
  { text: "不畏浮云遮望眼，自缘身在最高层。", source: "王安石《登飞来峰》" },
  { text: "纸上得来终觉浅，绝知此事要躬行。", source: "陆游《冬夜读书示子聿》" },
  { text: "问渠那得清如许？为有源头活水来。", source: "朱熹《观书有感》" },
  { text: "沉舟侧畔千帆过，病树前头万木春。", source: "刘禹锡《酬乐天扬州初逢席上见赠》" },
  { text: "博观而约取，厚积而薄发。", source: "苏轼《稼说送张琥》" },
  { text: "人生如逆旅，我亦是行人。", source: "苏轼《临江仙·送钱穆父》" },
  { text: "回首向来萧瑟处，归去，也无风雨也无晴。", source: "苏轼《定风波》" },
  { text: "且将新火试新茶，诗酒趁年华。", source: "苏轼《望江南·超然台作》" },
  { text: "竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。", source: "苏轼《定风波》" },
  { text: "一点浩然气，千里快哉风。", source: "苏轼《水调歌头·黄州快哉亭赠张偓佺》" },
  { text: "少年易老学难成，一寸光阴不可轻。", source: "朱熹《偶成》" },
  { text: "千淘万漉虽辛苦，吹尽狂沙始到金。", source: "刘禹锡《浪淘沙》" },
  { text: "会当凌绝顶，一览众山小。", source: "杜甫《望岳》" },
  { text: "读书破万卷，下笔如有神。", source: "杜甫《奉赠韦左丞丈二十二韵》" },
  { text: "何须浅碧深红色，自是花中第一流。", source: "李清照《鹧鸪天·桂花》" },
  { text: "等闲识得东风面，万紫千红总是春。", source: "朱熹《春日》" },
  { text: "试玉要烧三日满，辨材须待七年期。", source: "白居易《放言五首》" },
  { text: "野火烧不尽，春风吹又生。", source: "白居易《赋得古原草送别》" },
  { text: "看似寻常最奇崛，成如容易却艰辛。", source: "王安石《题张司业诗》" },
  { text: "路漫漫其修远兮，吾将上下而求索。", source: "屈原《离骚》" },
  { text: "亦余心之所善兮，虽九死其犹未悔。", source: "屈原《离骚》" },
  { text: "静以修身，俭以养德。", source: "诸葛亮《诫子书》" },
  { text: "非淡泊无以明志，非宁静无以致远。", source: "诸葛亮《诫子书》" },
  { text: "知之为知之，不知为不知，是知也。", source: "《论语·为政》" },
  { text: "工欲善其事，必先利其器。", source: "《论语·卫灵公》" },
  { text: "知者不惑，仁者不忧，勇者不惧。", source: "《论语·子罕》" },
  { text: "合抱之木，生于毫末；九层之台，起于累土。", source: "《道德经》" },
  { text: "千里之行，始于足下。", source: "《道德经》" },
  { text: "知人者智，自知者明。", source: "《道德经》" },
  { text: "苟日新，日日新，又日新。", source: "《礼记·大学》" },
  { text: "穷则变，变则通，通则久。", source: "《周易·系辞下》" },
  { text: "天行健，君子以自强不息。", source: "《周易》" },
  { text: "不积跬步，无以至千里；不积小流，无以成江海。", source: "《荀子·劝学》" },
  { text: "锲而不舍，金石可镂。", source: "《荀子·劝学》" },
  { text: "天地有大美而不言，四时有明法而不议，万物有成理而不说。", source: "《庄子·知北游》" },
  { text: "吾生也有涯，而知也无涯。", source: "《庄子·养生主》" },
  { text: "人生天地之间，若白驹之过隙，忽然而已。", source: "《庄子·知北游》" },
  { text: "知止而后有定，定而后能静，静而后能安，安而后能虑，虑而后能得。", source: "《礼记·大学》" },
  { text: "故天将降大任于是人也，必先苦其心志，劳其筋骨，饿其体肤，空乏其身。", source: "《孟子·告子下》" },
  { text: "君子生非异也，善假于物也。", source: "《荀子·劝学》" },
  { text: "日月忽其不淹兮，春与秋其代序。", source: "屈原《离骚》" },
  { text: "悟已往之不谏，知来者之可追。", source: "陶渊明《归去来兮辞》" },
  { text: "云无心以出岫，鸟倦飞而知还。", source: "陶渊明《归去来兮辞》" },
  { text: "木欣欣以向荣，泉涓涓而始流。", source: "陶渊明《归去来兮辞》" },
  { text: "仰观宇宙之大，俯察品类之盛，所以游目骋怀，足以极视听之娱。", source: "王羲之《兰亭集序》" },
  { text: "虽世殊事异，所以兴怀，其致一也。", source: "王羲之《兰亭集序》" },
  { text: "落霞与孤鹜齐飞，秋水共长天一色。", source: "王勃《滕王阁序》" },
  { text: "海上生明月，天涯共此时。", source: "张九龄《望月怀远》" },
  { text: "草木有本心，何求美人折。", source: "张九龄《感遇》" },
  { text: "江畔何人初见月？江月何年初照人？", source: "张若虚《春江花月夜》" },
  { text: "人生代代无穷已，江月年年望相似。", source: "张若虚《春江花月夜》" },
  { text: "江流天地外，山色有无中。", source: "王维《汉江临泛》" },
  { text: "大鹏一日同风起，扶摇直上九万里。", source: "李白《上李邕》" },
  { text: "莫道桑榆晚，为霞尚满天。", source: "刘禹锡《酬乐天咏老见示》" },
  { text: "正入万山圈子里，一山放出一山拦。", source: "杨万里《过松源晨炊漆公店》" },
  { text: "我见青山多妩媚，料青山见我应如是。", source: "辛弃疾《贺新郎》" },
  { text: "此心安处是吾乡。", source: "苏轼《定风波·南海归赠王定国侍人寓娘》" },
  { text: "胜固欣然，败亦可喜。优哉游哉，聊复尔耳。", source: "苏轼《观棋》" },
  { text: "山高月小，水落石出。", source: "苏轼《后赤壁赋》" },
  { text: "世界微尘里，吾宁爱与憎。", source: "李商隐《北青萝》" },
  { text: "The readiness is all.", source: "William Shakespeare, Hamlet" },
  { text: "To strive, to seek, to find, and not to yield.", source: "Alfred, Lord Tennyson, Ulysses" },
  { text: "Forever is composed of nows.", source: "Emily Dickinson" },
  { text: "Hope is the thing with feathers.", source: "Emily Dickinson" },
  { text: "The best way out is always through.", source: "Robert Frost" },
  { text: "What's past is prologue.", source: "William Shakespeare, The Tempest" },
  { text: "We know what we are, but know not what we may be.", source: "William Shakespeare, Hamlet" },
  { text: "This above all: to thine own self be true.", source: "William Shakespeare, Hamlet" },
  { text: "There is nothing either good or bad, but thinking makes it so.", source: "William Shakespeare, Hamlet" },
  { text: "Our doubts are traitors, and make us lose the good we oft might win, by fearing to attempt.", source: "William Shakespeare, Measure for Measure" },
  { text: "The fault, dear Brutus, is not in our stars, but in ourselves.", source: "William Shakespeare, Julius Caesar" },
  { text: "If I can stop one heart from breaking, I shall not live in vain.", source: "Emily Dickinson" },
  { text: "That it will never come again is what makes life so sweet.", source: "Emily Dickinson" },
  { text: "The woods are lovely, dark and deep, but I have promises to keep, and miles to go before I sleep.", source: "Robert Frost, Stopping by Woods on a Snowy Evening" },
  { text: "Two roads diverged in a wood, and I—I took the one less traveled by, and that has made all the difference.", source: "Robert Frost, The Road Not Taken" },
  { text: "I exist as I am, that is enough.", source: "Walt Whitman, Song of Myself" },
  { text: "The powerful play goes on, and you may contribute a verse.", source: "Walt Whitman, O Me! O Life!" },
  { text: "Do I contradict myself? Very well then I contradict myself; I am large, I contain multitudes.", source: "Walt Whitman, Song of Myself" },
  { text: "Nothing great was ever achieved without enthusiasm.", source: "Ralph Waldo Emerson" },
  { text: "Adopt the pace of nature: her secret is patience.", source: "Ralph Waldo Emerson" },
  { text: "Write it on your heart that every day is the best day in the year.", source: "Ralph Waldo Emerson" },
  { text: "We are all in the gutter, but some of us are looking at the stars.", source: "Oscar Wilde, Lady Windermere's Fan" },
  { text: "To define is to limit.", source: "Oscar Wilde, The Picture of Dorian Gray" },
  { text: "Experience is merely the name men gave to their mistakes.", source: "Oscar Wilde, The Picture of Dorian Gray" },
  { text: "It is not that we have a short time to live, but that we waste much of it.", source: "Seneca, On the Shortness of Life" },
  { text: "As long as you live, keep learning how to live.", source: "Seneca" },
  { text: "The heart has its reasons which reason knows nothing of.", source: "Blaise Pascal, Pensées" },
  { text: "Il faut cultiver notre jardin.", source: "Voltaire, Candide" },
  { text: "It is not enough to have a good mind; the main thing is to use it well.", source: "René Descartes, Discourse on the Method" },
  { text: "If I have seen further it is by standing on the shoulders of giants.", source: "Isaac Newton, letter to Robert Hooke" },
  { text: "Chance favors the prepared mind.", source: "Louis Pasteur" },
  { text: "Nothing in life is to be feared; it is only to be understood.", source: "Marie Curie" },
  { text: "The map is not the territory.", source: "Alfred Korzybski" },
  { text: "The limits of my language mean the limits of my world.", source: "Ludwig Wittgenstein, Tractatus Logico-Philosophicus" },
  { text: "Life can only be understood backwards; but it must be lived forwards.", source: "Søren Kierkegaard" },
  { text: "One must imagine Sisyphus happy.", source: "Albert Camus, The Myth of Sisyphus" },
  { text: "In the midst of winter, I found there was, within me, an invincible summer.", source: "Albert Camus, Return to Tipasa" },
  { text: "A book must be the axe for the frozen sea within us.", source: "Franz Kafka, letter to Oskar Pollak" },
  { text: "Live the questions now.", source: "Rainer Maria Rilke, Letters to a Young Poet" },
  { text: "What I cannot create, I do not understand.", source: "Richard Feynman" },
  { text: "All models are wrong, but some are useful.", source: "George E. P. Box" },
] as const

export function pickEmptyQuote() {
  return EMPTY_QUOTES[Math.floor(Math.random() * EMPTY_QUOTES.length)]
}
